#!/bin/bash 

# cases in shell-scripting 

echo
echo "Please choose one of the following options"
echo 
echo "a => Display Date and Time "
echo "b => List file and directories"
echo "c => List users logged in"
echo "d => Check System uptime"
echo

read choice

case $choice in

a) date;;
b) ls;;
c) who;;
d) uptime;;
*) echo "Invalid choice - Bye"

esac
