#!/bin/bash

host="100.86.20.102"
ping -c1 $host &> /dev/null		#to not show ping stats sue ping -c1 <id> &> /dev/null
	if [ $? -eq 0 ]; then
		echo "$host is Rechable"
	else
		echo "$host is NOT Rechable"
	fi
